services:
  - type: web
    name: ncsa-bharat-backend
    runtime: node
    plan: free
    region: singapore
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        sync: false
